events {}

http {
  server {
    root /usr/share/nginx/html;
    listen 8080;
    
    # reverse proxy to port 8000
    location / {
      proxy_pass http://app:8000;
    }
    location /api {
      proxy_pass http://app:8000;
    }
    
    # Serve static files in /data and block /data/graph-full.gexf as 403
    location /data {
      alias /usr/share/nginx/html/data;
      add_header Access-Control-Allow-Origin *;
    }

    location /data/graph-full.gexf {
      deny all;
      return 403;
    }
  }
}
